version: "3"

services:
  mongo:
    restart: unless-stopped
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - 'mongo_data:/data/db'

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  minio_data:
  mongo_data:

